; The very slick RAK wireless RAK 4631 / 4630 board - Unified firmware for 5005/19003, with or without OLED RAK 1921
[env:rak4631_paranode]
extends = nrf52840_base
board = wiscore_rak4631
board_level = pr
board_check = true
build_type = release
build_flags = ${nrf52840_base.build_flags}
  -I variants/nrf52840/diy/goneepic_paranode
  -D RAK_4631
  -DRADIOLIB_EXCLUDE_SX128X=1
  -DRADIOLIB_EXCLUDE_SX127X=1
  -DRADIOLIB_EXCLUDE_LR11X0=1
build_src_filter = ${nrf52_base.build_src_filter} \
  +<../variants/nrf52840/diy/goneepic_paranode> \
  +<mesh/eth/> \
  +<mesh/api/> \
  +<mqtt/> \
  -<graphics/EInkDisplay2.cpp> \
  -<graphics/EInkDynamicDisplay.cpp> \
  -<graphics/fonts/EinkDisplayFonts.cpp>
lib_deps = 
  ${nrf52840_base.lib_deps}
  melopero/Melopero RV3028@^1.1.0
  https://github.com/RAKWireless/RAK13800-W5100S/archive/1.0.2.zip
  ; rakwireless/RAKwireless NCP5623 RGB LED library@^1.0.2
  ; beegee-tokyo/RAK12035_SoilMoisture@^1.0.4
  # renovate: datasource=git-refs depName=RAK12034-BMX160 packageName=https://github.com/RAKWireless/RAK12034-BMX160 gitBranch=main
  https://github.com/RAKWireless/RAK12034-BMX160/archive/dcead07ffa267d3c906e9ca4a1330ab989e957e2.zip


[env:goneepic_paranode]
extends = env:rak4631_paranode
build_type = release
board_level = extra

build_flags =
  ${env:rak4631_paranode.build_flags}
  -D MESHTASTIC_EXCLUDE_MQTT
  -D GPS_L76K
; build_unflags = -DHAS_NCP5623
build_src_filter = ${env:rak4631_paranode.build_src_filter}

[env:goneepic_paranode_flamingo]
extends = env:rak4631_paranode
board_level = extra

build_flags =
  ${env:rak4631_paranode.build_flags}
  -D FLAMINGO

