; Flamingo variants for commercial nodes 
[env:heltec-mesh-node-t114_flamingo]
extends = env:heltec-mesh-node-t114

build_flags =
  ${env:heltec-mesh-node-t114.build_flags}
  -D FLAMINGO

lib_deps =
  ${env:heltec-mesh-node-t114.lib_deps}

[env:seeed_solar_node_flamingo]
extends = env:seeed_solar_node
board_level = extra

build_flags =
  ${env:seeed_solar_node.build_flags}
  -D FLAMINGO
  -DSNR_MINIMUM=3.0
  ; -D FLAMINGO_BLINKY
  ;-D MESHTASTIC_EXCLUDE_MQTT
  ;-D MESHTASTIC_EXCLUDE_GPS

lib_deps =
  ${env:seeed_solar_node.lib_deps}

[env:heltec-v3_flamingo]
extends = env:heltec-v3

build_flags =
  ${env:heltec-v3.build_flags}
  -D FLAMINGO

lib_deps =
  ${env:heltec-v3.lib_deps}

[env:heltec-v4_flamingo]
extends = env:heltec-v4

build_flags =
  ${env:heltec-v4.build_flags}
  -D FLAMINGO

lib_deps =
  ${env:heltec-v4.lib_deps}

[env:t-deck-tft_flamingo]
extends = env:t-deck-tft

build_flags =
  ${env:t-deck-tft.build_flags}
  -D FLAMINGO

lib_deps =
  ${env:t-deck-tft.lib_deps}

[env:r1-neo_flamingo]
extends = env:r1-neo

build_flags =
  ${env:r1-neo.build_flags}
  -D FLAMINGO
  
lib_deps =
  ${env:r1-neo.lib_deps}

[env:t-echo_flamingo]
extends = env:t-echo

build_flags =
  ${env:t-echo.build_flags}
  -D FLAMINGO
  
lib_deps =
  ${env:t-echo.lib_deps}

[env:rak_wismeshtag_flamingo]
extends = env:rak_wismeshtag

build_flags =
  ${env:rak_wismeshtag.build_flags}
  -D FLAMINGO
  -D MESHTASTIC_EXCLUDE_MQTT

lib_deps =
  ${env:rak_wismeshtag.lib_deps}
 
[env:tracker-t1000-e_flamingo]
extends = env:tracker-t1000-e

build_flags =
  ${env:tracker-t1000-e.build_flags}
  -D FLAMINGO

lib_deps =
  ${env:tracker-t1000-e.lib_deps}

[env:seeed_xiao_nrf52840_sense_flamingo] ; also works on seeed xiao senses
extends = env:seeed_xiao_nrf52840_kit

build_flags =
  ${env:seeed_xiao_nrf52840_kit.build_flags}
  -D FLAMINGO
; build_unflags = -DGPS_L76K


lib_deps =
  ${env:seeed_xiao_nrf52840_kit.lib_deps}

; [env:seeed_xiao_nrf52840_kit_flamingo] ; also works on seeed xiao senses
; extends = env:seeed_xiao_nrf52840_kit

; build_flags =
;   ${env:seeed_xiao_nrf52840_kit.build_flags}
;   -D FLAMINGO

; lib_deps =
;   ${env:seeed_xiao_nrf52840_kit.lib_deps}

